version: '3'
services: 
  db:
    image: postgres:9.6
  web:
    environment:
      - USER
      - UID
      - HOME
      - SHELL
    build:
      context: .
      args:
        USER: $USER
        UID: $UID
        SHELL: $SHELL
        $HOME: $HOME
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/PhotoApp
    ports:
      - "3000:3000"
    depends_on:
      - db

